### ISSUE TITLE
Show/hide recipe bug

### ISSUE THREAD

**Issue by muRn** [pestbarn/obsidian#8]
I'm not a big beer fan but I really like the idea of keeping website code opensource. Since repository looks active (not abandoned) I decided to share the bug I've found.

When `Show recipe` button is pressed on any beer card, *all* `Show recipe` buttons are changed to `Hide recipe`. In my understanding only pressed button should be changed.

For example, I pressed `Show recipe` on the first beer card and then scrolled down:
<img width="501" alt="изображение" src="https://user-images.githubusercontent.com/2263591/106365966-32b5e800-6339-11eb-8817-e945ab568617.png">
As you can see, recipe is hidden for this beer, however button caption is still `Hide recipe`.

**Comment by pestbarn** [comment]
> When `Show recipe` button is pressed on any beer card, _all_ `Show recipe` buttons are changed to `Hide recipe`. In my understanding only pressed button should be changed.

Thanks for even taking the time to open an issue, I wasn't even aware people were visiting :) I've dirty-fixed the issue for now, will work on a proper fix as soon as I can be arsed to.
